allprojects {
    repositories {
        google()
        mavenCentral()
        // Required for com.github.yausername:youtubedl-android (yt-dlp for Android)
        maven { url 'https://jitpack.io' }
    }
}

rootProject.buildDir = "../build"
subprojects {
    project.buildDir = "${rootProject.buildDir}/${project.name}"
}
subprojects {
    project.evaluationDependsOn(":app")
}

tasks.register("clean", Delete) {
    delete rootProject.buildDir
}
